### ISSUE TITLE
Thingsboard custom rule nodes - Failed to load configuration ui resources

### ISSUE THREAD

**Issue by marbrune** [thingsboard/rule-node-examples#11] opened 2022-03-14 11:41 UTC
I created a custom RuleNode following https://thingsboard.io/docs/user-guide/contribution/rule-node-development/
customizing also the component ui starting from rule-node-examples-ui-ngx project.
When I deploy and run Thingsboard, the custom RuleNode is visible, but not the form. The error says: "Failed to load configuration ui resources"

In rule-node-examples project I defined directive like this:
configDirective = "tbExternalNodeCustomRestApiCallConfig"

In rule-node-examples-ui-ngx project I defined component selector in component ts file like this:
selector: 'tb-external-node-custom-rest-api-call-config'

Is it necessary to define directive in other places or something similar?

**Comment by skewty** [comment] 2022-08-09 14:20
Is this a duplicate of #3?

**Comment by marbrune** [comment] 2022-08-23 07:31
> Is this a duplicate of #3?

Maybe, even if I'm not sure the error was exactly the same.
Anyway, I'm no longer on the project where I tried this.

**Comment by skewty** [comment] 2022-08-23 13:21
@marbrune perhaps you could close out the issue then to help the TB developers prioritise their time?

**Closed** 2022-08-23 13:24 UTC
